run:
  tests: false
linters:
  enable:
    - nilerr
    - bodyclose
    - gofmt
    - revive
    - govet
    - gosec
linters-settings:
  gofmt:
    simplify: false
issues:
  exclude-use-default: false
  exclude:
    # errcheck: Almost all programs ignore errors on these functions and in most cases it's ok
    - Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv). is not checked
    # golint
    - func name will be used as test\.Test.* by other packages, and that stutters; consider calling this
