version: "2"

run:
  go: '1.24'
  timeout: 2m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - nilerr
    - staticcheck
    - unused
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - unused
      - linters:
          - errcheck
        text: "Error return value of .*.Close"
      - linters:
          - staticcheck
        text: "ST1005:|SA1029:|QF1012:"

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/adlio/schema
