run:
  go: '1.18'
  timeout: 2m

linters:
  enable:
    - errcheck
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - nilerr
    - staticcheck
    - typecheck
    - unused

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/adlio/schema

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
